Testing grunt
vitali-usik/training-ng-grunt pull request #6
Opened 2017-03-23 06:35 UTC by IgorSinyak

2017-03-28 15:10 UTC, vitali-usik requested changes

2017-03-28 15:10 UTC, vitali-usik commented on scripts/controllers.js
> +      if ($scope.checked === event.target.value) {
If the type of $scope.checked is boolean you needn't to write `if ($scope.checked === event.target.value)`. Just `if ($scope.checked)`

2017-03-28 15:10 UTC, vitali-usik commented on scripts/controllers.js
> +    $scope.dropdownValue = 'Dropdown';
It'd be better if you initialize all values in the top of controller. Then functions with blank line like separator. It'll increase readability of code

2017-03-28 15:10 UTC, vitali-usik commented on scripts/controllers.js
> +        $scope.showDropdown = true;
Can you simplify to $scope.showDropdown = !$scope.showDropdown ?

2017-03-28 15:10 UTC, vitali-usik commented on scss/views/contactus.scss
> +        -moz-appearance: none;
You can add something like autoprefixer, that can do it on compilation phase

2017-03-28 15:10 UTC, vitali-usik commented on views/contactus.html
> +        <li class="select-item"><a href="#" class="active">Lorem Ipsum</a></li>
Is that element always has class='active' or it's dynamically changing?

2017-03-28 15:10 UTC, vitali-usik commented on views/contactus.html
> +      <form class="contactus-form" name="contact" ng-submit="sendForm()" novalidate>
You need to add 'data-' prefix for all non-html attrs

2017-03-28 15:10 UTC, vitali-usik commented on views/contactus.html
> +            <input type="file" id="load-photo" name="load-photo" ng-model="contactForm.photo">
As above

2017-03-28 15:10 UTC, vitali-usik commented on views/contactus.html
> +              <option value="375">375</option>
It'd be better to pass an array of options in ng-repeat

2017-03-28 15:10 UTC, vitali-usik commented on views/contactus.html
> +              <option value="37">37</option>
As above

2017-03-28 15:10 UTC, vitali-usik commented on views/contactus.html
> +              <option value="3754">3754</option>
As above

2017-03-28 15:10 UTC, vitali-usik commented on views/footer.html
> +            <li class="option"><a href="" ng-click="selectOption($event)">Option4</a></li>
As above

2017-03-29 05:57 UTC, IgorSinyak commented on scripts/controllers.js
> +      if ($scope.checked === event.target.value) {
ok, agree with you

2017-03-29 06:03 UTC, IgorSinyak commented on scripts/controllers.js
> +    $scope.dropdownValue = 'Dropdown';
ok, agree, while studying angular, hard to control code style, i`ll correct code

2017-03-29 06:11 UTC, IgorSinyak commented on scss/views/contactus.scss
> +        -moz-appearance: none;
in grunt?

2017-03-29 06:11 UTC, IgorSinyak commented on views/contactus.html
> +        <li class="select-item"><a href="#" class="active">Lorem Ipsum</a></li>
it dynamically changes, i added it for look style in browser

2017-03-29 06:12 UTC, IgorSinyak commented on views/contactus.html
> +      <form class="contactus-form" name="contact" ng-submit="sendForm()" novalidate>
'data-ng-submit', and so for all ng directives?

2017-03-29 06:15 UTC, IgorSinyak commented on scripts/controllers.js
> +        $scope.showDropdown = true;
don`t understand, "onclick = function() { $scope.showDropdown = !$scope.showDropdown}", right?

2017-03-29 06:17 UTC, IgorSinyak commented on scripts/controllers.js
> +      if ($scope.checked === event.target.value) {
this function don`t need here at all, i forgot to delete it =)

2017-03-29 10:42 UTC, vitali-usik commented on scripts/controllers.js
> +        $scope.showDropdown = true;
yep

2017-03-29 10:42 UTC, vitali-usik commented on scss/views/contactus.scss
> +        -moz-appearance: none;
yep

2017-03-29 10:43 UTC, vitali-usik commented on views/contactus.html
> +        <li class="select-item"><a href="#" class="active">Lorem Ipsum</a></li>
You can use angular variable like { 'active': isActive() }. Don't you?

2017-03-29 10:43 UTC, vitali-usik commented on views/contactus.html
> +      <form class="contactus-form" name="contact" ng-submit="sendForm()" novalidate>
yep

2017-04-17 17:21 UTC, merged